### ISSUE TITLE
dataディレクトリ内のファイルを読み込む際のprefixの有無

### ISSUE THREAD

**Issue by wakuteka** [IshidaMotohiro/ADC#1]
pull requestにすべきか迷ったのですが、方針がわからないのでissueを立てさせていただきました。

dataディレクトリ内のファイルを読み込む際のprefixの有無が、Chapter1とそれ以外で違うようです。
Rスクリプトごとに異なるのはわかるのですが、Chapter03.Rではdata/ありとなしが混在しているのでそこだけでも統一したほうが親切かと思いました。

https://github.com/IshidaMotohiro/ADC/commit/7d8d7642550e18a9aba474e9cd77e8e0eb7a84cc#diff-a3bca321cb53d92477c3ac51989fcf60R128　（あり）

https://github.com/IshidaMotohiro/ADC/commit/7d8d7642550e18a9aba474e9cd77e8e0eb7a84cc#diff-a3bca321cb53d92477c3ac51989fcf60R126　（なし）

ご確認よろしくおねがいします。

**Comment by wakuteka** [comment]
関連して、原著のコード通りではあるのですが、Chapter13.Rの

https://github.com/IshidaMotohiro/ADC/blob/7d8d7642550e18a9aba474e9cd77e8e0eb7a84cc/Chapter13.R#L5 

にて、Chapter13.Rのあるディレクトリで実行しDataディレクトリを作ろうとした時に、data/とフォルダ名が衝突してしまう気がします。

**Comment by Kudo-wakana** [comment]
ご指摘ありがとうございます。
Chapter3.Rについては、data/ありに統一する形で対応致します。

**Comment by shinichi-takayanagi** [comment]
Chapter13.R、衝突はやむ無しでそのままいきたいので、”該当ディレクトリがなければ作成”に切り替えます！

**Comment by IshidaMotohiro** [comment]
@wakuteka  ありがとうございます。
これはすべてのスクリプトにおいてデータフォルダとして "data/" を追加修正する方向で調整いたします。
