### ISSUE TITLE
誤字報告

### ISSUE THREAD

**Issue by dichika** [IshidaMotohiro/ADC#2]
誤字を見つけたのでご報告します。
ご確認のほどよろしくお願いします。

- p120 XpathSApply()→xpathSApply()　：２カ所
- p412 beging.http→begins.http

**Comment by shinichi-takayanagi** [comment]
[正誤表](https://github.com/IshidaMotohiro/ADC/wiki/%E6%AD%A3%E8%AA%A4%E8%A1%A8) にマージしたのでCloseします！
