### ISSUE TITLE
typo報告

### ISSUE THREAD

**Issue by wakuteka** [IshidaMotohiro/ADC#3]
typoを見つけたのでご報告します。
ご確認のほどよろしくお願いします。

ページ|誤|正
------------ | -------------|------------ 
p.295|strigr|stringr
p.305（節タイトル）|RHTMForms|RHTMLForms

**Comment by IshidaMotohiro** [comment]
ありがとうございます。(正誤表)[https://github.com/IshidaMotohiro/ADC/wiki/%E6%AD%A3%E8%AA%A4%E8%A1%A8] に反映させていただきます。
